# Generated by Django 2.0.2 on 2018-03-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('origin_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('current_location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('current_location_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('last_stoppage_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('last_stoppage_lot', models.DecimalField(decimal_places=6, max_digits=9)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('speed', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=12)),
                ('driver', models.OneToOneField(on_delete=models.SET('NO_DRIVER'), to='dashboard.Driver')),
                ('trip', models.OneToOneField(on_delete=models.SET('NO_DRIVER'), to='dashboard.Trip')),
            ],
        ),
    ]
