# Generated by Django 2.0.2 on 2018-03-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_first_name', models.CharField(max_length=15)),
                ('driver_last_name', models.CharField(max_length=15)),
                ('driver_contact', models.CharField(max_length=10)),
                ('truck_number', models.CharField(default='', max_length=12)),
                ('origin_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('origin_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('current_location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('current_location_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('last_stoppage_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('last_stoppage_lot', models.DecimalField(decimal_places=6, max_digits=9)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('speed', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='truck',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='trip',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='Truck',
        ),
    ]
